### PR TITLE
displaylink fix: ignore primary argument when using evdi drivers

### LINKED ISSUE #22: Displaylink/Evdi not working (monitors detected, no signal/black screen)
Similar issue to wlroots, Displaylink/EVDI is not supported out of the box for Intel iGPU on Hyprland. All 3 of my monitors are detected by `hyprctl monitors`, but they do not receive signals (black screen).

The wlroots issue is detailed [here](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/1823).

Would be great if there is a robust way to support this.

---

A quick workaround similar to [what I posted on wlroots-hyprland](https://github.com/hyprwm/wlroots-hyprland/issues/14#issuecomment-2200550019) is by changing aquamarine's `src/backend/drm/DRM.cpp`, line 208 of commit `601f6cf95cbe4fef02dc7faf34bba58566c914e9`, from
```cpp
if (!drmBackend->registerGPU(gpu, newPrimary)) {
```
to
```cpp
if (!drmBackend->registerGPU(gpu, {})) {
```
See the full diff in [this commit here](https://github.com/nktnet1/aquamarine/commit/db3c0dca6e4e7f297d2bf25560f5bb35518c603b). This is related to [Hyprland issue 2752](https://github.com/hyprwm/Hyprland/issues/2752#issuecomment-2200593220).

Do note the same limitations exists, as [mentioned by Kacper Zuk on GitLab](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/1823#note_1254398):
> *This hack disables support for multi GPU, so [aquamarine] doesn't try to initialize renderers on DisplayLink devices.*

---

### Full Specs:
| Category | Value |
|-|-|
| OS | Arch Linux x86_64 |
| Host | Predator PHN16-71 (V1.15) |
| Kernel | Linux 6.9.9-arch1-1 |
| Display (LG FULL HD) | 1920x1080 @ 60Hz |
| Display (HP LA2206) | 1920x1080 @ 60Hz |
| Display (BOE0A2C) | 2560x1600 @ 60Hz (as 1602x1001) [Built-in] |
| WM | Hyprland (Wayland) |
| CPU | 13th Gen Intel(R) Core(TM) i9-13900HX (32) @ 5.40 GHz |
| GPU | Intel Raptor Lake-S UHD Graphics @ 1.65 GHz [Integrated] |

Hybrid laptop with NVIDIA dGPU disabled (only using Intel iGPU).

### PR DESCRIPTION
**Pull request by nktnet1**
Fixes #22.

A slightly more robust way to address the issue than the hack provided in #22 - done by checking if the driver being used for the given GPU is `evdi`. If so, set `primary` to `{}`.

Unsure of the following:
- whether this still falls under "hacky code" mentioned in Hyprland's [PR Guidelines](https://wiki.hyprland.org/Contributing-and-Debugging/PR-Guidelines/#pr-requirements)
- variables like `drmName` and `drmVer` are `auto` instead of `auto const` - have followed the same convention for the newly introduced `drmVerName` variable
- whether there exist use cases with `evdi` drivers and using the passed-in `primary_` argument (I assume no)

### CODE REVIEW

**Comment by vaxerski** [comment]
hm, I am no kernel dev, but this will essentially force KMS to take buffers from your primary gpu instead of them living on evdi.

I have no clue if that has any ramifications for the user.

If it works fine and others can attest to that, I'm fine with this.

File: src/backend/drm/DRM.cpp [hunk 1]
```diff
@@ -599,8 +599,13 @@ bool Aquamarine::CDRMBackend::registerGPU(SP<CSessionDevice> gpu_, SP<CDRMBacken
 
     gpuName = drmName;
 
+    auto drmVerName = drmVer->name ? drmVer->name : "unknown";
+    if (std::string_view(drmVerName) == "evdi") {
```
Comment (vaxerski) [inline src/backend/drm/DRM.cpp:603]: no {}

**Comment by nktnet1** [comment]
Thanks @vaxerski - I've fixed the style issue. Running clang-format also modified `tests/SimpleWindow.cpp` - happy to revert if that should be done in a different MR.

> I have no clue if that has any ramifications for the user.

I'm uncertain of this too - my assumption based on what I've read and researched thus far is that evdi is incapable of rendering:
image


> If it works fine and others can attest to that, I'm fine with this.

I think it's working fairly well for those on wlroots:
evidence-users

and here's a reply to the previous version of my patch (although effectively the same changes):
- https://github.com/hyprwm/Hyprland/issues/2752#issuecomment-2242770323

**Comment by nktnet1** [comment]
Adding to findings above, I've also tested this patch with the nvidia-gpu re-enabled

Here are the logs:
- [patched-with-nvidia.log](https://github.com/user-attachments/files/16362419/patched-with-nvidia.log)

`lspci` and `/dev/dri/by-path`:
image

<details close>
<summary>Text output</summary>

```sh
~$ lspci | grep -E 'VGA|3D'
0000:00:02.0 VGA compatible controller: Intel Corporation Raptor Lake-S UHD Graphics (rev 04)
0000:01:00.0 VGA compatible controller: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] (rev a1)
~$ ls -l /dev/dri/by-path  
total 0
lrwxrwxrwx 1 root root  8 Jul 24 22:55 pci-0000:00:02.0-card -> ../card1
lrwxrwxrwx 1 root root 13 Jul 24 22:55 pci-0000:00:02.0-render -> ../renderD128
lrwxrwxrwx 1 root root  8 Jul 24 22:55 pci-0000:01:00.0-card -> ../card0
lrwxrwxrwx 1 root root 13 Jul 24 22:55 pci-0000:01:00.0-render -> ../renderD129
lrwxrwxrwx 1 root root  8 Jul 24 22:55 platform-evdi.0-card -> ../card2
lrwxrwxrwx 1 root root  8 Jul 24 22:55 platform-evdi.1-card -> ../card3
~$ 
```

</details>

**Comment by vaxerski** [comment]
> Running clang-format also modified tests/SimpleWindow.cpp - happy to revert if that should be done in a different MR

ye please do, I should remove it anyways its broken

**Comment by nktnet1** [comment]
> > Running clang-format also modified tests/SimpleWindow.cpp - happy to revert if that should be done in a different MR
> 
> ye please do, I should remove it anyways its broken

Have been reverted :)
